insert into public.projects (
  slug,
  category,
  title,
  short_description,
  tech,
  image_url,
  github_url,
  live_url,
  featured,
  problem,
  process,
  results
)
values
  (
    'mobile-banking-redesign',
    'ui-ux',
    'Mobile Banking Redesign',
    'A modern UX redesign to improve account visibility and transaction flow.',
    array['Figma', 'Design System', 'User Testing'],
    'https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/your-username/mobile-banking-redesign',
    'https://your-domain.com/mobile-banking-redesign',
    true,
    'Users struggled to quickly find key account actions and balances.',
    'I ran user journey mapping, built wireframes, and iterated high-fidelity prototypes.',
    'Task completion time was reduced and user clarity improved across key screens.'
  ),
  (
    'dashboard-wireframe-kit',
    'ui-ux',
    'Dashboard Wireframe Kit',
    'Reusable wireframe system for analytics and management dashboards.',
    array['Figma', 'UX Research', 'Prototyping'],
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/your-username/dashboard-wireframe-kit',
    'https://your-domain.com/dashboard-wireframe-kit',
    false,
    'Teams were designing dashboard layouts from scratch repeatedly.',
    'I built a reusable structure with standard cards, filters, and chart placements.',
    'Design cycles became faster and layout consistency improved significantly.'
  ),
  (
    'taskflow-app',
    'web-app',
    'TaskFlow Web App',
    'A productivity app with task boards, filtering, and clean visual hierarchy.',
    array['React', 'Tailwind', 'REST API'],
    'https://images.unsplash.com/photo-1611224923853-80b023f02d71?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/your-username/taskflow-app',
    'https://your-domain.com/taskflow-app',
    true,
    'Project teams needed a lightweight planner with quick status tracking.',
    'I designed reusable card components, route-based views, and keyboard-friendly UX.',
    'Users could plan weekly tasks faster with fewer clicks and clearer status visibility.'
  ),
  (
    'analytics-hub',
    'web-app',
    'Analytics Hub',
    'Interactive KPI dashboard with widgets, charts, and responsive sections.',
    array['React', 'Chart.js', 'Tailwind'],
    'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/your-username/analytics-hub',
    'https://your-domain.com/analytics-hub',
    false,
    'Stakeholders lacked a unified and accessible view of key business metrics.',
    'Built modular chart cards and clean filtering controls for various screen sizes.',
    'Decision-making improved through at-a-glance dashboards and better data readability.'
  ),
  (
    'portfolio-cms',
    'full-stack',
    'Portfolio CMS',
    'Full-stack portfolio platform with admin panel and content publishing.',
    array['React', 'Supabase', 'Tailwind'],
    'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/your-username/portfolio-cms',
    'https://your-domain.com/portfolio-cms',
    true,
    'Portfolio updates took too long due to manual code changes.',
    'Built CRUD APIs, media support, and a simple content editor for rapid publishing.',
    'New projects can now be published in minutes instead of hours.'
  ),
  (
    'inventory-manager',
    'full-stack',
    'Inventory Manager',
    'Inventory and supplier tracking system with audit logs and role access.',
    array['React', 'Express', 'PostgreSQL'],
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/your-username/inventory-manager',
    'https://your-domain.com/inventory-manager',
    false,
    'Manual stock tracking caused delayed updates and inaccurate item counts.',
    'Created secure APIs, transactional updates, and role-based dashboard pages.',
    'Stock accuracy improved and teams gained reliable real-time inventory visibility.'
  )
on conflict (slug) do update set
  category = excluded.category,
  title = excluded.title,
  short_description = excluded.short_description,
  tech = excluded.tech,
  image_url = excluded.image_url,
  github_url = excluded.github_url,
  live_url = excluded.live_url,
  featured = excluded.featured,
  problem = excluded.problem,
  process = excluded.process,
  results = excluded.results;
